/**
 * Icelandic postal codes → locality (staður) + municipality (sveitarfélag).
 * Seed/reference data (SPEC §5): covers the residential postal codes used in
 * practice; PO-box-only codes are omitted. Extend as needed — the table is
 * upserted by code on every seed run.
 */
export interface PostalCodeSeed {
  code: string;
  locality: string;
  municipality: string;
}

export const POSTAL_CODES: PostalCodeSeed[] = [
  // Höfuðborgarsvæðið
  { code: "101", locality: "Reykjavík", municipality: "Reykjavíkurborg" },
  { code: "102", locality: "Reykjavík", municipality: "Reykjavíkurborg" },
  { code: "103", locality: "Reykjavík", municipality: "Reykjavíkurborg" },
  { code: "104", locality: "Reykjavík", municipality: "Reykjavíkurborg" },
  { code: "105", locality: "Reykjavík", municipality: "Reykjavíkurborg" },
  { code: "107", locality: "Reykjavík", municipality: "Reykjavíkurborg" },
  { code: "108", locality: "Reykjavík", municipality: "Reykjavíkurborg" },
  { code: "109", locality: "Reykjavík", municipality: "Reykjavíkurborg" },
  { code: "110", locality: "Reykjavík", municipality: "Reykjavíkurborg" },
  { code: "111", locality: "Reykjavík", municipality: "Reykjavíkurborg" },
  { code: "112", locality: "Reykjavík", municipality: "Reykjavíkurborg" },
  { code: "113", locality: "Reykjavík", municipality: "Reykjavíkurborg" },
  { code: "116", locality: "Reykjavík", municipality: "Reykjavíkurborg" },
  { code: "170", locality: "Seltjarnarnes", municipality: "Seltjarnarnesbær" },
  { code: "200", locality: "Kópavogur", municipality: "Kópavogsbær" },
  { code: "201", locality: "Kópavogur", municipality: "Kópavogsbær" },
  { code: "203", locality: "Kópavogur", municipality: "Kópavogsbær" },
  { code: "206", locality: "Kópavogur", municipality: "Kópavogsbær" },
  { code: "210", locality: "Garðabær", municipality: "Garðabær" },
  { code: "220", locality: "Hafnarfjörður", municipality: "Hafnarfjarðarkaupstaður" },
  { code: "221", locality: "Hafnarfjörður", municipality: "Hafnarfjarðarkaupstaður" },
  { code: "225", locality: "Garðabær (Álftanes)", municipality: "Garðabær" },
  { code: "270", locality: "Mosfellsbær", municipality: "Mosfellsbær" },
  { code: "271", locality: "Mosfellsbær", municipality: "Mosfellsbær" },
  { code: "276", locality: "Mosfellsbær", municipality: "Mosfellsbær" },
  // Suðurnes
  { code: "190", locality: "Vogar", municipality: "Sveitarfélagið Vogar" },
  { code: "230", locality: "Reykjanesbær", municipality: "Reykjanesbær" },
  { code: "232", locality: "Reykjanesbær", municipality: "Reykjanesbær" },
  { code: "233", locality: "Reykjanesbær", municipality: "Reykjanesbær" },
  { code: "235", locality: "Keflavíkurflugvöllur", municipality: "Reykjanesbær" },
  { code: "240", locality: "Grindavík", municipality: "Grindavíkurbær" },
  { code: "245", locality: "Sandgerði", municipality: "Suðurnesjabær" },
  { code: "250", locality: "Garður", municipality: "Suðurnesjabær" },
  { code: "260", locality: "Reykjanesbær", municipality: "Reykjanesbær" },
  // Vesturland
  { code: "300", locality: "Akranes", municipality: "Akraneskaupstaður" },
  { code: "301", locality: "Akranes", municipality: "Akraneskaupstaður" },
  { code: "310", locality: "Borgarnes", municipality: "Borgarbyggð" },
  { code: "311", locality: "Borgarnes", municipality: "Borgarbyggð" },
  { code: "320", locality: "Reykholt í Borgarfirði", municipality: "Borgarbyggð" },
  { code: "340", locality: "Stykkishólmur", municipality: "Stykkishólmsbær" },
  { code: "350", locality: "Grundarfjörður", municipality: "Grundarfjarðarbær" },
  { code: "355", locality: "Ólafsvík", municipality: "Snæfellsbær" },
  { code: "356", locality: "Snæfellsbær", municipality: "Snæfellsbær" },
  { code: "360", locality: "Hellissandur", municipality: "Snæfellsbær" },
  { code: "370", locality: "Búðardalur", municipality: "Dalabyggð" },
  // Vestfirðir
  { code: "380", locality: "Reykhólahreppur", municipality: "Reykhólahreppur" },
  { code: "400", locality: "Ísafjörður", municipality: "Ísafjarðarbær" },
  { code: "401", locality: "Ísafjörður", municipality: "Ísafjarðarbær" },
  { code: "410", locality: "Hnífsdalur", municipality: "Ísafjarðarbær" },
  { code: "415", locality: "Bolungarvík", municipality: "Bolungarvíkurkaupstaður" },
  { code: "420", locality: "Súðavík", municipality: "Súðavíkurhreppur" },
  { code: "425", locality: "Flateyri", municipality: "Ísafjarðarbær" },
  { code: "430", locality: "Suðureyri", municipality: "Ísafjarðarbær" },
  { code: "450", locality: "Patreksfjörður", municipality: "Vesturbyggð" },
  { code: "460", locality: "Tálknafjörður", municipality: "Vesturbyggð" },
  { code: "465", locality: "Bíldudalur", municipality: "Vesturbyggð" },
  { code: "470", locality: "Þingeyri", municipality: "Ísafjarðarbær" },
  // Norðurland vestra
  { code: "510", locality: "Hólmavík", municipality: "Strandabyggð" },
  { code: "530", locality: "Hvammstangi", municipality: "Húnaþing vestra" },
  { code: "540", locality: "Blönduós", municipality: "Húnabyggð" },
  { code: "545", locality: "Skagaströnd", municipality: "Skagabyggð" },
  { code: "550", locality: "Sauðárkrókur", municipality: "Skagafjörður" },
  { code: "560", locality: "Varmahlíð", municipality: "Skagafjörður" },
  { code: "565", locality: "Hofsós", municipality: "Skagafjörður" },
  { code: "580", locality: "Siglufjörður", municipality: "Fjallabyggð" },
  // Norðurland eystra
  { code: "600", locality: "Akureyri", municipality: "Akureyrarbær" },
  { code: "601", locality: "Akureyri", municipality: "Akureyrarbær" },
  { code: "603", locality: "Akureyri", municipality: "Akureyrarbær" },
  { code: "605", locality: "Akureyri", municipality: "Akureyrarbær" },
  { code: "610", locality: "Grenivík", municipality: "Grýtubakkahreppur" },
  { code: "620", locality: "Dalvík", municipality: "Dalvíkurbyggð" },
  { code: "625", locality: "Ólafsfjörður", municipality: "Fjallabyggð" },
  { code: "640", locality: "Húsavík", municipality: "Norðurþing" },
  { code: "650", locality: "Laugar", municipality: "Þingeyjarsveit" },
  { code: "660", locality: "Mývatn", municipality: "Þingeyjarsveit" },
  { code: "670", locality: "Kópasker", municipality: "Norðurþing" },
  { code: "675", locality: "Raufarhöfn", municipality: "Norðurþing" },
  { code: "680", locality: "Þórshöfn", municipality: "Langanesbyggð" },
  { code: "690", locality: "Vopnafjörður", municipality: "Vopnafjarðarhreppur" },
  // Austurland
  { code: "700", locality: "Egilsstaðir", municipality: "Múlaþing" },
  { code: "701", locality: "Egilsstaðir", municipality: "Múlaþing" },
  { code: "710", locality: "Seyðisfjörður", municipality: "Múlaþing" },
  { code: "720", locality: "Borgarfjörður eystri", municipality: "Múlaþing" },
  { code: "730", locality: "Reyðarfjörður", municipality: "Fjarðabyggð" },
  { code: "735", locality: "Eskifjörður", municipality: "Fjarðabyggð" },
  { code: "740", locality: "Neskaupstaður", municipality: "Fjarðabyggð" },
  { code: "750", locality: "Fáskrúðsfjörður", municipality: "Fjarðabyggð" },
  { code: "755", locality: "Stöðvarfjörður", municipality: "Fjarðabyggð" },
  { code: "760", locality: "Breiðdalsvík", municipality: "Fjarðabyggð" },
  { code: "765", locality: "Djúpivogur", municipality: "Múlaþing" },
  { code: "780", locality: "Höfn í Hornafirði", municipality: "Sveitarfélagið Hornafjörður" },
  // Suðurland
  { code: "800", locality: "Selfoss", municipality: "Sveitarfélagið Árborg" },
  { code: "801", locality: "Selfoss", municipality: "Sveitarfélagið Árborg" },
  { code: "810", locality: "Hveragerði", municipality: "Hveragerðisbær" },
  { code: "815", locality: "Þorlákshöfn", municipality: "Sveitarfélagið Ölfus" },
  { code: "820", locality: "Eyrarbakki", municipality: "Sveitarfélagið Árborg" },
  { code: "825", locality: "Stokkseyri", municipality: "Sveitarfélagið Árborg" },
  { code: "840", locality: "Laugarvatn", municipality: "Bláskógabyggð" },
  { code: "845", locality: "Flúðir", municipality: "Hrunamannahreppur" },
  { code: "850", locality: "Hella", municipality: "Rangárþing ytra" },
  { code: "860", locality: "Hvolsvöllur", municipality: "Rangárþing eystra" },
  { code: "870", locality: "Vík í Mýrdal", municipality: "Mýrdalshreppur" },
  { code: "880", locality: "Kirkjubæjarklaustur", municipality: "Skaftárhreppur" },
  { code: "900", locality: "Vestmannaeyjar", municipality: "Vestmannaeyjabær" },
];
